# Changes here will be overwritten by Copier.
_commit: 1.14.0
_src_path: gh:pawamoy/copier-uv
author_email: dev@pawamoy.fr
author_fullname: Timothée Mazzucotelli
author_username: pawamoy
copyright_date: '2015'
copyright_holder: Timothée Mazzucotelli
copyright_holder_email: dev@pawamoy.fr
copyright_license: ISC
project_description: A command line tool that helps you remembering ALL the numerous keyboard shortcuts of ALL your favorite programs.
project_name: keycut
python_package_command_line_name: keycut
python_package_distribution_name: keycut
python_package_import_name: keycut
repository_name: keycut
repository_namespace: pawamoy
repository_provider: github.com
