# Changes here will be overwritten by Copier
_commit: 322f694
_src_path: https://github.com/pawamoy/copier-poetry.git
author_email: pawamoy@pm.me
author_fullname: "Timoth\xE9e Mazzucotelli"
author_username: pawamoy
copyright_date: '2015'
copyright_holder: "Timoth\xE9e Mazzucotelli"
copyright_holder_email: timothee.mazzucotelli@pm.me
copyright_license: ISC License
project_description: A command line tool that helps you remembering ALL the numerous
  keyboard shortcuts of ALL your favorite programs.
project_name: keycut
python_package_command_line_name: keycut
python_package_distribution_name: keycut
python_package_import_name: keycut
repository_name: keycut
repository_namespace: pawamoy
repository_provider: github.com
